#+TITLE: Bienvenue chez NNotes

* Bienvenue dans le projet NNotes

  Vous venez de discuter avec au moins un membre de l'équipe NNotes et il vous a
  remis ce fichier.  Après avoir discuté, il est maintenant temps de mettre les
  mains dans le cambouis !



** Le projet

   NNotes propose à chacun d'assimiler/publier des connaissances de niveau
   universitaire, et d'être rémunéré pour le faire.  À travers sa plate-forme
   web, NNotes s'attaque à certains problèmes liés à
   l'assimilation/publication : coût de production, de partage, de mise à jour,
   et d'assimilation des connaissances.

   NNotes et le fond d'investissement IT-translation se réunissent une fois par
   semaine pour faire de la plate-forme web actuelle le coeur d'une nouvelle façon
   de créer et transmettre des connaissances et d'être rémunéré pour le faire.

   Concrètement, NNotes à besoin de compléter l'équipe d'ici juin prochain.  Nous
   espérons la compléter avec quelques-uns d'entre vous.



** Le deal

   L'équipe NNotes discute avec vous de projets à implémenter et vous vous mettez
   d'accord sur l'un d'entre eux.

   Pendant l'implémentation du projet, n'hésitez pas à solliciter l'équipe
   NNotes.  Le projet sera éventuellement intégré à la plate-forme NNotes, au
   plus tard en juillet prochain.

   Si le projet que vous aurez implémenté est intégré à la plate-forme NNotes
   alors nous discuterons de sa rémunération, de la poursuite par un stage,
   voire d'un recrutement comme membre à part entière de l'équipe NNotes.

   Si le projet n'est pas intégré à la plate-forme NNotes alors vous aurez
   bénéficié de tous nos efforts pour vous faire toucher du doigts la création,
   le développement et potentiellement le crash ou la réussite d'une startup.
   Nous vous encourageons déjà de retenter votre chance avec nous !



** L'entreprise

   Nous suivons les traces de Valve, jetez un coup d'oeil à leur gestion de
   l'entreprise, ça vaut le détour :-).

   [[http://www.valvesoftware.com/company/Valve_Handbook_LowRes.pdf][Valve handbook]]

   Nous avons bien conscience que Valve est quelques centaines d'employés,
   quelques milliards et quelques immenses succès au loin.  La route est longue,
   mais nous espérons nous rapprocher d'eux.

   En attendant, voici notre propre
   [[https://github.com/nomosyn/resources/][NNotes handbook]], largement inspiré
   du leur.




** Implémenter un projet

*** The tale of two bridges

    Two old engineers were talking of their lives and boasting of their
    greatest projects. One of the engineers explained how he had designed the
    largest bridge ever made.

    "We built it across a river gorge," he told his friend. "It was wide and
    deep. We spent two years studying the land, and choosing designs. Then we
    hired the best people and designed the bridge, which took another five
    years. We contracted the largest engineering firms to build the structures,
    the towers, the tollbooths, and the roads that would connect the bridge to
    the main highways. Under the road level we had trains, and a special path
    for cyclists. That bridge represented years of my life."

    The second man reflected for a while, then spoke. "One evening me and a
    friend threw a rope across a gorge," he said. "Just a rope, tied to two
    trees. There were two villages, one at each side. At first, people pulled
    packages across that rope with a pulley and string. Then someone pulled
    across a second rope, and built a foot walk. It was dangerous, but the kids
    loved it. A group of men then rebuilt that, made it solid, and women
    started to cross, everyday, with their produce. A market grew up on one
    side of the bridge, and slowly that became a large town, since there was a
    lot of space for houses. The rope bridge got replaced with a wooden bridge,
    to allow horses and carts to cross. Then the town built a real stone
    bridge, with metal beams. Later, they replaced the stone part with steel,
    and today there's a suspension bridge standing in that same spot."

    The first engineer was silent. "Funny thing," he said, "my bridge was
    demolished not long after it was built. Turns out it was built in the wrong
    place and no-one wanted to use it. Some bastard had thrown a rope across
    the gorge, a few miles further downstream, and that's where everyone went."

    This article is an extract from Chapter 6 of the [[http://shop.oreilly.com/product/0636920026136.do][ZeroMQ book]], on community
    building.



*** Modalités

    - Une fois que nous nous serons mis d'accord sur le projet à implémenter, si
      possible, trouvez au moins une autre personne avec qui avancer.

    - En cas de problème n'hésitez pas à nous contacter
      (frohring.pierrehenry@gmail.com, contact@bastienfaure.fr) et jetez un oeil
      au [[https://github.com/nomosyn/resources/][NNotes handbook]]


    - Implémentez le projet sur GitHub !
        - $ [[https://www.meteor.com/][meteor]] create my-project

        - Gestion du projet: [[http://rfc.zeromq.org/spec:22][C4.1]]

        - Licence: [[https://www.mozilla.org/MPL/2.0/][MPLv2]]

        - Coding style: [[https://github.com/nomosyn/resources/][JS coding style]]
